import Link from 'next/link'

const PRIMARY = '#9B8EC4'
const BEIGE = '#FAF7F2'
const BEIGE_CARD = '#FFFFFF'
const BEIGE_BORDER = '#E8E2D9'
const TEXT = '#2D2D2D'
const TEXT_MUTED = '#9E9188'

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', fontFamily: 'system-ui, sans-serif', color: TEXT, background: BEIGE }}>

      {/* Nav */}
      <nav style={{ background: BEIGE_CARD, borderBottom: `2px solid ${BEIGE_BORDER}`, padding: '16px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, zIndex: 100, boxShadow: '0 1px 4px rgba(0,0,0,0.05)' }}>
        <Link href="/landing" style={{ fontFamily: 'Georgia,serif', fontSize: 20, fontWeight: 700, color: TEXT, textDecoration: 'none' }}>
          🧭 Waypoint <span style={{ color: PRIMARY }}>Education</span>
        </Link>
        <Link href="/landing" style={{ fontSize: 14, fontWeight: 700, color: TEXT_MUTED, textDecoration: 'none' }}>← Back</Link>
      </nav>

      <div style={{ maxWidth: 760, margin: '0 auto', padding: '64px 24px' }}>
        <h1 style={{ fontFamily: 'Georgia,serif', fontSize: 40, marginBottom: 8, color: TEXT }}>Terms of Service</h1>
        <p style={{ color: TEXT_MUTED, fontSize: 14, marginBottom: 48 }}>Last updated: 22 March 2026</p>

        <div style={{ background: BEIGE_CARD, borderRadius: 20, padding: '40px 48px', border: `2px solid ${BEIGE_BORDER}`, boxShadow: '0 1px 6px rgba(0,0,0,0.04)' }}>

          <Section title="1. About these terms">
            <p>These Terms of Service ("Terms") govern your use of Waypoint Education, a service operated by Jonatan Ekström, Sweden ("we", "us", "our"). By creating an account or using the service you agree to these Terms.</p>
            <p>These Terms are governed by Swedish law. Any disputes shall be resolved in the courts of Sweden.</p>
          </Section>

          <Section title="2. The service">
            <p>Waypoint Education provides AI-powered lesson planning, interactive worksheets, a travel journal, and related educational tools designed for homeschooling families.</p>
            <p>We reserve the right to modify, suspend, or discontinue the service (or any part of it) at any time with reasonable notice. We will not be liable to you for any such modification, suspension, or discontinuation.</p>
          </Section>

          <Section title="3. Eligibility">
            <p>You must be at least 18 years old to create an account. By registering, you confirm that you are an adult and, where you provide child profile information, that you are that child's parent or legal guardian.</p>
            <p>The service is intended for personal, non-commercial family use. Use by schools or other institutions requires prior written agreement with us.</p>
          </Section>

          <Section title="4. Account">
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. Notify us immediately at <a href="mailto:jonatan.ekstrom@gmail.com" style={{ color: PRIMARY }}>jonatan.ekstrom@gmail.com</a> if you suspect unauthorised access.</p>
            <p>You may not share your account with others or create multiple accounts to circumvent any limitations or free trial terms.</p>
          </Section>

          <Section title="5. Free trial and subscription">
            <p>Your subscription includes a 10-day free trial. A card is required at signup but you will not be charged until after the trial ends.</p>
            <p>After the free trial, continued use of the service requires a paid subscription. Subscription fees are billed in advance on a monthly, quarterly, or annual basis depending on the plan you select.</p>
            <p>Prices are displayed in EUR. You are responsible for any applicable taxes in your jurisdiction.</p>
            <p>You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. We do not offer prorated refunds for partial billing periods unless required by applicable law.</p>
          </Section>

          <Section title="6. Acceptable use">
            <p>You agree not to:</p>
            <ul>
              <li>Use the service for any unlawful purpose or in violation of any applicable law or regulation.</li>
              <li>Attempt to gain unauthorised access to any part of the service or its infrastructure.</li>
              <li>Reverse engineer, decompile, or otherwise attempt to extract source code from the service.</li>
              <li>Use automated tools (bots, scrapers, etc.) to access or extract content from the service without our written consent.</li>
              <li>Use the service to generate content that is harmful, abusive, or inappropriate for children.</li>
              <li>Resell, sublicense, or otherwise commercialise any content generated by the service.</li>
            </ul>
          </Section>

          <Section title="7. AI-generated content">
            <p>Lesson plans, worksheets, journal entries, and other content are generated using AI models. While we strive for accuracy and quality, AI-generated content may contain errors, inaccuracies, or material that requires parental review before use with children.</p>
            <p>You are responsible for reviewing all AI-generated content before using it as part of your child's education. We do not guarantee that the content meets any particular educational standard or curriculum requirement.</p>
            <p>Content generated through your use of the service is owned by you, subject to the underlying AI provider's terms. We do not claim ownership over lesson plans, worksheets, or journal entries generated for your family.</p>
          </Section>

          <Section title="8. Intellectual property">
            <p>The Waypoint Education name, logo, website design, and underlying software are our intellectual property and may not be copied, reproduced, or used without our prior written consent.</p>
            <p>Any feedback, suggestions, or ideas you submit to us may be used by us to improve the service without any obligation to compensate you.</p>
          </Section>

          <Section title="9. Privacy">
            <p>Our collection and use of personal data is described in our <Link href="/privacy" style={{ color: PRIMARY }}>Privacy Policy</Link>, which forms part of these Terms. By using the service you agree to our Privacy Policy.</p>
          </Section>

          <Section title="10. Disclaimers">
            <p>The service is provided "as is" and "as available" without warranties of any kind, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>
            <p>We do not warrant that the service will be uninterrupted, error-free, or that any defects will be corrected. Educational outcomes depend on many factors beyond the service, and we make no representations about results.</p>
          </Section>

          <Section title="11. Limitation of liability">
            <p>To the maximum extent permitted by Swedish law, our total liability to you for any claims arising out of or relating to these Terms or the service shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
            <p>We are not liable for indirect, incidental, special, consequential, or punitive damages, including loss of data or loss of profits, even if we have been advised of the possibility of such damages.</p>
            <p>Nothing in these Terms limits liability that cannot be excluded under applicable Swedish consumer protection law.</p>
          </Section>

          <Section title="12. Changes to these terms">
            <p>We may update these Terms from time to time. We will notify you of material changes by email or by a prominent notice within the app at least 14 days before the changes take effect. Continued use of the service after the effective date constitutes acceptance of the updated Terms.</p>
            <p>If you do not agree to the updated Terms, you may cancel your subscription and stop using the service.</p>
          </Section>

          <Section title="13. Governing law and disputes">
            <p>These Terms are governed by the laws of Sweden, without regard to its conflict of law provisions. Any dispute arising under or relating to these Terms shall be subject to the exclusive jurisdiction of the Swedish courts.</p>
            <p>If you are a consumer based in the EU, you may also have the right to use the EU Online Dispute Resolution platform at <a href="https://ec.europa.eu/consumers/odr" style={{ color: PRIMARY }} target="_blank" rel="noopener noreferrer">ec.europa.eu/consumers/odr</a>.</p>
          </Section>

          <Section title="14. Contact">
            <p>Questions about these Terms? Contact us at:</p>
            <p style={{ marginTop: 12 }}>
              <strong>Jonatan Ekström</strong><br />
              Waypoint Education<br />
              Sweden<br />
              <a href="mailto:jonatan.ekstrom@gmail.com" style={{ color: PRIMARY }}>jonatan.ekstrom@gmail.com</a>
            </p>
          </Section>

        </div>
      </div>

      {/* Footer */}
      <div style={{ background: TEXT, padding: '32px 24px', textAlign: 'center' }}>
        <span style={{ fontFamily: 'Georgia,serif', fontSize: 18, fontWeight: 700, color: 'white' }}>🧭 Waypoint <span style={{ color: PRIMARY }}>Education</span></span>
        <p style={{ color: '#9E9188', fontSize: 13, marginTop: 8, marginBottom: 12 }}>© 2026 Waypoint Education · The world is their classroom.</p>
        <div style={{ display: 'flex', gap: 24, justifyContent: 'center' }}>
          <Link href="/privacy" style={{ color: '#9E9188', fontSize: 13, textDecoration: 'none' }}>Privacy Policy</Link>
          <Link href="/terms" style={{ color: '#9E9188', fontSize: 13, textDecoration: 'none' }}>Terms of Service</Link>
        </div>
      </div>

    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{ fontFamily: 'Georgia,serif', fontSize: 22, color: '#2D2D2D', marginBottom: 16, paddingBottom: 10, borderBottom: `2px solid #E8E2D9` }}>{title}</h2>
      <div style={{ fontSize: 15, lineHeight: 1.8, color: '#2D2D2D' }}>
        {children}
      </div>
    </div>
  )
}
